<?php

	include_once("includes/db_mysql.php");
set_time_limit(0);
	$db = new DB_Sql();
	$mb = new DB_Sql();
	$mb1 = new DB_Sql();
	/*
//20,21,22,23,24,25,26,27,28 - designation for support

	$sSQL = "Select id, ADDTIME (ADDTIME (ADDTIME (ADDTIME (if(break1_out < break1_in ,ADDTIME(TIMEDIFF('24:00:00',break1_in), break1_out),TIMEDIFF(break1_out,break1_in)) ,if(break2_out < break2_in,ADDTIME(TIMEDIFF('24:00:00',break2_in), break2_out), TIMEDIFF(break2_out,break2_in))),if(break3_out < break3_in,ADDTIME(TIMEDIFF('24:00:00',break3_in), break3_out), TIMEDIFF(break3_out,break3_in))),if(break4_out < break4_in,ADDTIME(TIMEDIFF('24:00:00',break4_in), break4_out), TIMEDIFF(break4_out,break4_in))),if(break5_out < break5_in,ADDTIME(TIMEDIFF('24:00:00',break5_in), break5_out), TIMEDIFF(break5_out,break5_in))) AS totalbreak, if(ADDTIME (ADDTIME (ADDTIME (ADDTIME (if(break1_out < break1_in ,ADDTIME(TIMEDIFF('24:00:00',break1_in), break1_out),TIMEDIFF(break1_out,break1_in)),if(break2_out < break2_in,ADDTIME(TIMEDIFF('24:00:00',break2_in), break2_out), TIMEDIFF(break2_out,break2_in))),if(break3_out < break3_in,ADDTIME(TIMEDIFF('24:00:00',break3_in), break3_out), TIMEDIFF(break3_out,break3_in))),if(break4_out < break4_in,ADDTIME(TIMEDIFF('24:00:00',break4_in), break4_out), TIMEDIFF(break4_out,break4_in))),if(break5_out < break5_in,ADDTIME(TIMEDIFF('24:00:00',break5_in), break5_out), TIMEDIFF(break5_out,break5_in))) > '00:45:00','1','0') as isExceeded from pms_attendance where user_id in (163,164,165,166,167,168,169,170,171,172,182)";
	$db->query($sSQL);
	if($db->num_rows())
	{
		while($db->next_record())
		{
			$arrUpdate["id"] = $db->f("id");
			$arrUpdate["total_break_time"] = $db->f("totalbreak");
			$arrUpdate["isExceededBreak"] = $db->f("isExceeded");
			
			$Actual_exceedTime = "00:00:00";
			if($db->f("isExceeded") == '1')
			{
				$exceedTime = strtotime(Date('Y-m-d')." ".$db->f("totalbreak")) - strtotime(Date('Y-m-d')." 00:45:00");
				
				$Actual_exceedTime = gmdate("H:i:s", $exceedTime);
			}
			
			$arrUpdate["break_exceed_time"] = $Actual_exceedTime;
			
			//print_r($arrUpdate);
			$mb->updateArray("pms_attendance",$arrUpdate);
		}
	}*/
	
	
	/* Fix shift time for attendance for autogenerated roster */
	$sSQL = "SELECT r.userid, rd . *, date_format(rostereddate,'%Y-%m-%d')  as rdate
FROM  `pms_roster_detail` rd
INNER JOIN pms_roster r ON r.id = rd.rosterid
WHERE rd.`rostereddate` 
BETWEEN  '2013-05-13 00:00:00'
AND  '2013-05-19 00:00:00'
AND r.`autoadded` ='1'";

	$db->query($sSQL);
	if($db->num_rows())
	{
		while($db->next_record())
		{
			unset($arrUpdate);

			$arrUpdate["user_id"] = $db->f("userid");
			$arrUpdate["date"] = $db->f("rdate");
			$arrUpdate["shift_id"] = $db->f("shiftid");

			$sSQL = "select * from pms_attendance where date_format(date,'%Y-%m-%d') = '".$db->f("rdate")."' and user_id='".$db->f("userid")."'";
			$mb1->query($sSQL);
			if($mb1->num_rows() == 0)
			{
				//Insert
				$mb->insertArray("pms_attendance",$arrUpdate);
			}
			else
			{
				if($mb1->next_record())
				{
					$arrUpdate["id"] = $mb1->f("id");
					$mb->updateArray("pms_attendance",$arrUpdate);
				}
				else
				{
					$mb->insertArray("pms_attendance",$arrUpdate);
				}
			}
			
			//print_r($arrUpdate);
		}
	}

	echo "done";

?>
